---
abstract: 'Session store in memcached with JSON serialization'
author:
  - 'Forest Belton <forest@homolo.gy>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-Memcached-JSON
requires:
  Cache::Memcached: 0
  Dancer::Config: 0
  Dancer::Session::Abstract: 0
  Digest::SHA: 0
  Exporter: 0
  Function::Parameters: 0
  JSON: 0
  base: 0
  strict: 0
  warnings: 0
version: 0.003
